apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flight-tracker

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - beat-deployment.yaml
  - ingress.yaml

commonLabels:
  app: flight-tracker
  managed-by: kustomize
